spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    http:
      multipart:
        enabled: true
        file-size-threshold: 2MB
  application:
    name: reserva-tu-cancha-backend
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database:3306/rtc-bd
    username: appdb
    password: secret
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
security:
  jwt:
    expire_ms: 86400000
    key:
      private: 26817a8e89a986f9a0f85b133397133fc7f3ff94ea901b3eb2ea0c0042104646
    user:
      generator: RTC-BACKEND
aws:
  accessKeyId:
  secretKey:
  bucketName: